---
- hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    http_port: 80
    domain: lifestream.dev
  roles:
  - apt
  - mysql
  - apache
  tasks:
  - hostname: name={{ domain }}

- hosts: all
  remote_user: vagrant
  roles:
  - python